import { jsPDF } from 'jspdf';
import type { AuditFormData } from '../../types/form';
import type { AnalysisResponse, PillarAnalysis } from '../../types/analysis';
import { sanitizeText } from '../sanitizeText';
import { PDF_COLORS, SEVERITY_COLORS } from './pdfStyles';

function drawPageBackground(doc: jsPDF) {
  doc.setFillColor(...PDF_COLORS.darkBg);
  doc.rect(0, 0, 210, 297, 'F');
}

function drawGoldLine(doc: jsPDF, y: number) {
  doc.setDrawColor(...PDF_COLORS.gold);
  doc.setLineWidth(0.5);
  doc.line(20, y, 190, y);
}

function drawFooter(doc: jsPDF) {
  doc.setFontSize(7);
  doc.setTextColor(...PDF_COLORS.lightGray);
  doc.text('Generated by ManTech Designs LLC | profitleakfix.com', 105, 287, { align: 'center' });
  doc.text('This audit is an educational tool. Financial figures are illustrative and do not guarantee specific results.', 105, 291, { align: 'center' });
}

function wrapText(doc: jsPDF, text: string, maxWidth: number): string[] {
  return doc.splitTextToSize(sanitizeText(text), maxWidth);
}

function drawPillarRow(doc: jsPDF, name: string, analysis: PillarAnalysis, y: number): number {
  const severityColor = SEVERITY_COLORS[analysis.severity] || PDF_COLORS.lightGray;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PDF_COLORS.white);
  doc.text(sanitizeText(name), 20, y);

  doc.setTextColor(...severityColor);
  doc.setFontSize(10);
  doc.text(analysis.severity.toUpperCase() + ' RISK', 110, y);

  doc.setTextColor(...PDF_COLORS.gold);
  doc.text('$' + analysis.leakAmount.toLocaleString() + '/year', 160, y);

  return y + 8;
}

export async function generateProfitLeakPdf(
  formData: AuditFormData,
  analysis: AnalysisResponse
): Promise<Blob> {
  const doc = new jsPDF('p', 'mm', 'a4');
  const firstName = formData.firstName || 'Business Owner';
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  // PAGE 1 - Cover + Scorecard
  drawPageBackground(doc);

  doc.setFontSize(10);
  doc.setTextColor(...PDF_COLORS.lightGray);
  doc.text('AI-Assisted & The Business Resilience Revolution', 105, 25, { align: 'center' });

  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PDF_COLORS.gold);
  doc.text('PROFIT LEAK REPORT', 105, 45, { align: 'center' });

  doc.setFontSize(12);
  doc.setTextColor(...PDF_COLORS.white);
  doc.text(sanitizeText(`Prepared for: ${firstName}`), 105, 58, { align: 'center' });
  doc.setFontSize(9);
  doc.setTextColor(...PDF_COLORS.lightGray);
  doc.text(date, 105, 65, { align: 'center' });

  drawGoldLine(doc, 75);

  doc.setFontSize(10);
  doc.setTextColor(...PDF_COLORS.lightGray);
  doc.text('This report estimates hidden revenue loss using conservative benchmarks', 105, 82, { align: 'center' });
  doc.text('based on your revenue tier.', 105, 88, { align: 'center' });

  // Scorecard
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PDF_COLORS.gold);
  doc.text('PROFIT LEAK SCORECARD', 105, 105, { align: 'center' });

  let y = 120;
  y = drawPillarRow(doc, 'Lead Generation', analysis.pillars.leadGeneration, y);
  drawGoldLine(doc, y);
  y += 6;
  y = drawPillarRow(doc, 'Sales System', analysis.pillars.salesFollowUp, y);
  drawGoldLine(doc, y);
  y += 6;
  y = drawPillarRow(doc, 'Branding & Authority', analysis.pillars.authorityBranding, y);
  drawGoldLine(doc, y);
  y += 6;
  y = drawPillarRow(doc, 'Retention & LTV', analysis.pillars.retentionLTV, y);
  drawGoldLine(doc, y);
  y += 10;

  // Total
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PDF_COLORS.white);
  doc.text('ESTIMATED TOTAL ANNUAL LEAK:', 20, y);
  doc.setTextColor(...PDF_COLORS.gold);
  doc.setFontSize(18);
  doc.text('$' + analysis.totalAnnualLeak.toLocaleString(), 190, y, { align: 'right' });

  y += 15;

  // Leak Distribution
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PDF_COLORS.gold);
  doc.text('Leak Distribution', 20, y);
  y += 8;

  const pillars = [
    { name: 'Sales', pct: analysis.pillars.salesFollowUp.leakPercentage },
    { name: 'Lead Gen', pct: analysis.pillars.leadGeneration.leakPercentage },
    { name: 'Branding', pct: analysis.pillars.authorityBranding.leakPercentage },
    { name: 'Retention', pct: analysis.pillars.retentionLTV.leakPercentage },
  ];

  for (const p of pillars) {
    doc.setFontSize(9);
    doc.setTextColor(...PDF_COLORS.white);
    doc.text(sanitizeText(`${p.name}: ${Math.round(p.pct)}%`), 20, y);
    y += 6;
  }

  drawFooter(doc);

  // PAGE 2 - Detailed Results
  doc.addPage();
  drawPageBackground(doc);

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PDF_COLORS.gold);
  doc.text('YOUR PROFIT LEAK ANALYSIS', 105, 25, { align: 'center' });

  y = 40;

  const pillarEntries: [string, PillarAnalysis][] = [
    ['Lead Generation', analysis.pillars.leadGeneration],
    ['Sales Follow-Up', analysis.pillars.salesFollowUp],
    ['Authority & Branding', analysis.pillars.authorityBranding],
    ['Retention & LTV', analysis.pillars.retentionLTV],
  ];

  for (const [name, pillar] of pillarEntries) {
    const severityColor = SEVERITY_COLORS[pillar.severity] || PDF_COLORS.lightGray;

    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...PDF_COLORS.white);
    doc.text(sanitizeText(name), 20, y);

    doc.setFontSize(9);
    doc.setTextColor(...severityColor);
    doc.text(pillar.severity.toUpperCase() + ' RISK', 120, y);

    doc.setTextColor(...PDF_COLORS.gold);
    doc.text('$' + pillar.leakAmount.toLocaleString() + '/year', 160, y);

    y += 7;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...PDF_COLORS.lightGray);
    const explanationLines = wrapText(doc, pillar.explanation, 170);
    doc.text(explanationLines, 20, y);
    y += explanationLines.length * 4 + 3;

    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...PDF_COLORS.gold);
    doc.text('Recommendation:', 20, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...PDF_COLORS.white);
    const recLines = wrapText(doc, pillar.recommendation, 150);
    doc.text(recLines, 52, y);
    y += recLines.length * 4 + 5;

    drawGoldLine(doc, y);
    y += 8;

    if (y > 260) {
      doc.addPage();
      drawPageBackground(doc);
      y = 25;
    }
  }

  // Recovery message
  y += 5;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PDF_COLORS.white);
  const recoveryLines = wrapText(
    doc,
    `Even if you recovered just half of this over the next 12 months, that's an extra $${Math.round(analysis.totalAnnualLeak / 2).toLocaleString()} in profit - without increasing ad spend or working more hours.`,
    170
  );
  doc.text(recoveryLines, 20, y);

  drawFooter(doc);

  // PAGE 3 - Action Plan
  doc.addPage();
  drawPageBackground(doc);

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PDF_COLORS.gold);
  doc.text('YOUR ACTION PLAN', 105, 25, { align: 'center' });

  doc.setFontSize(11);
  doc.setTextColor(...PDF_COLORS.white);
  doc.text(sanitizeText("Here's what you should do right now to fix this:"), 20, 38);

  y = 50;

  analysis.actionSteps.forEach((step, i) => {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...PDF_COLORS.gold);
    doc.text(sanitizeText(`${i + 1}. ${step.title}`), 20, y);
    y += 7;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...PDF_COLORS.lightGray);
    const descLines = wrapText(doc, step.description, 170);
    doc.text(descLines, 20, y);
    y += descLines.length * 4 + 3;

    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...PDF_COLORS.white);
    doc.text(sanitizeText(`Timeframe: ${step.timeframe}`), 20, y);
    y += 5;

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...PDF_COLORS.green);
    doc.text(sanitizeText(`Expected Impact: ${step.expectedImpact}`), 20, y);
    y += 10;

    if (y > 250) {
      doc.addPage();
      drawPageBackground(doc);
      y = 25;
    }
  });

  // Priority box
  y += 5;
  doc.setFillColor(30, 30, 30);
  doc.setDrawColor(...PDF_COLORS.gold);
  doc.roundedRect(20, y, 170, 25, 3, 3, 'FD');

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PDF_COLORS.white);
  doc.text('If you only fix ONE thing in the next 30 days, fix this:', 25, y + 10);

  doc.setTextColor(...PDF_COLORS.gold);
  doc.text(sanitizeText('-> ' + analysis.bestImmediateFix), 25, y + 18);

  drawFooter(doc);

  // PAGE 4 - Next Steps
  doc.addPage();
  drawPageBackground(doc);

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PDF_COLORS.gold);
  doc.text('NEXT STEPS', 105, 25, { align: 'center' });

  y = 45;

  // Option 1
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PDF_COLORS.white);
  doc.text('Option 1: Figure It Out Yourself', 20, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...PDF_COLORS.lightGray);
  const opt1Lines = wrapText(doc, "Use this report as a roadmap. 6-12 months of trial and error, you're still the bottleneck. Cost: your time and every dollar that leaks while you build.", 170);
  doc.text(opt1Lines, 20, y);
  y += opt1Lines.length * 4 + 8;

  // Option 2
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PDF_COLORS.white);
  doc.text('Option 2: Hire 5 Separate Agencies', 20, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...PDF_COLORS.lightGray);
  const opt2Lines = wrapText(doc, "One for each system. $8K-$25K/month, 12+ months, you become the project manager. Cost: retainers + you're still the bottleneck.", 170);
  doc.text(opt2Lines, 20, y);
  y += opt2Lines.length * 4 + 8;

  // Option 3
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PDF_COLORS.gold);
  doc.text('Option 3: Let Us Show You How to Patch These Leaks', 20, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...PDF_COLORS.white);
  const opt3Lines = wrapText(doc, 'This is exactly what our $5K/$12K programs fix for you. Same systems behind clients uncovering $716K in pipeline revenue and adding $640K in profit.', 170);
  doc.text(opt3Lines, 20, y);
  y += opt3Lines.length * 4 + 12;

  // CTA 1
  drawGoldLine(doc, y);
  y += 8;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PDF_COLORS.gold);
  doc.text('WATCH THE FREE TRAINING', 20, y);
  y += 6;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...PDF_COLORS.lightGray);
  doc.text('"How to Patch These Profit Leaks Fast" - 15-minute walkthrough', 20, y);
  y += 5;
  doc.setTextColor(...PDF_COLORS.white);
  doc.textWithLink('https://profitleakfix.com/stopleaks-1', 20, y, {
    url: 'https://profitleakfix.com/stopleaks-1',
  });
  y += 12;

  // CTA 2
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PDF_COLORS.gold);
  doc.text('BOOK A LIVE STRATEGY SESSION', 20, y);
  y += 6;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...PDF_COLORS.lightGray);
  doc.text('We walk through this report together, map out your 30-90 day fix plan.', 20, y);
  y += 5;
  doc.text('No charge, no obligation.', 20, y);
  y += 5;
  doc.setTextColor(...PDF_COLORS.white);
  doc.textWithLink('https://ai.mantechdesigns.com/widget/bookings/resilience', 20, y, {
    url: 'https://ai.mantechdesigns.com/widget/bookings/resilience',
  });
  y += 15;

  // Closing
  drawGoldLine(doc, y);
  y += 8;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...PDF_COLORS.lightGray);
  const closingLines = wrapText(doc, '"Every day you wait is another day this revenue leaks. The money is already flowing through your business. Now decide how fast you want to collect it."', 170);
  doc.text(closingLines, 20, y);

  drawFooter(doc);

  return doc.output('blob');
}
