import { jsPDF } from 'jspdf';
import type { AuditResult, PillarResult } from '../calculations';
import { getPillarCopy } from '../pillarCopy';
import { QUIZ_SECTIONS } from '../../data/questions';

const COLORS = {
  darkBg: [13, 27, 42] as [number, number, number],
  cardBg: [17, 24, 39] as [number, number, number],
  gold: [212, 168, 67] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  lightGray: [160, 174, 192] as [number, number, number],
  cyan: [0, 212, 255] as [number, number, number],
  teal: [0, 212, 170] as [number, number, number],
  red: [255, 71, 87] as [number, number, number],
  orange: [255, 107, 53] as [number, number, number],
  yellow: [255, 217, 61] as [number, number, number],
  green: [0, 200, 83] as [number, number, number],
};

function getRiskColor(risk: string): [number, number, number] {
  switch (risk) {
    case 'HIGH': return COLORS.red;
    case 'MEDIUM-HIGH': return COLORS.orange;
    case 'MEDIUM': return COLORS.yellow;
    case 'LOW': return COLORS.green;
    default: return COLORS.lightGray;
  }
}

function safe(text: string): string {
  return text
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2013\u2014]/g, '-')
    .replace(/[^\x20-\x7E\n]/g, '');
}

function drawBg(doc: jsPDF) {
  doc.setFillColor(...COLORS.darkBg);
  doc.rect(0, 0, 210, 297, 'F');
}

function drawFooter(doc: jsPDF) {
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.lightGray);
  doc.text('Generated by ManTech Designs LLC | profitleakfix.com', 105, 287, { align: 'center' });
  doc.text('This audit is an educational tool. Financial figures are illustrative and do not guarantee specific results.', 105, 291, { align: 'center' });
}

function drawLine(doc: jsPDF, y: number) {
  doc.setDrawColor(...COLORS.gold);
  doc.setLineWidth(0.5);
  doc.line(20, y, 190, y);
}

function wrap(doc: jsPDF, text: string, maxW: number): string[] {
  return doc.splitTextToSize(safe(text), maxW);
}

function getSelectedAnswer(pillarId: string, scores: Record<string, number>): string {
  const section = QUIZ_SECTIONS.find((s) => s.id === pillarId);
  if (!section) return '';
  const option = section.options.find((o) => o.score === scores[pillarId]);
  return option?.text || '';
}

export async function generateProfitLeakPdfV2(
  firstName: string,
  result: AuditResult,
  scores: Record<string, number>,
): Promise<Blob> {
  const doc = new jsPDF('p', 'mm', 'a4');
  const name = firstName || 'Business Owner';
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  // === PAGE 1: Cover + Scorecard ===
  drawBg(doc);

  doc.setFontSize(10);
  doc.setTextColor(...COLORS.lightGray);
  doc.text('AI-Powered Analysis by Business Resilience Revolution', 105, 25, { align: 'center' });

  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.gold);
  doc.text('Your Profit Leak Report', 105, 45, { align: 'center' });

  doc.setFontSize(12);
  doc.setTextColor(...COLORS.white);
  doc.text(safe('Prepared for: ' + name), 105, 58, { align: 'center' });
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.lightGray);
  doc.text(date, 105, 65, { align: 'center' });

  drawLine(doc, 75);

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.gold);
  doc.text('PROFIT LEAK SCORECARD', 105, 90, { align: 'center' });

  let y = 105;
  for (const pillar of result.pillars) {
    const riskColor = getRiskColor(pillar.risk);

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.white);
    doc.text(safe(pillar.name), 20, y);

    doc.setTextColor(...riskColor);
    doc.setFontSize(10);
    doc.text(pillar.risk + ' RISK', 110, y);

    doc.setTextColor(...COLORS.gold);
    doc.text('$' + pillar.leakAmount.toLocaleString() + '/year', 160, y);

    y += 6;
    drawLine(doc, y);
    y += 8;
  }

  y += 4;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.white);
  doc.text('ESTIMATED TOTAL ANNUAL LEAK:', 20, y);
  doc.setTextColor(...COLORS.cyan);
  doc.setFontSize(18);
  doc.text('$' + result.totalLeak.toLocaleString(), 190, y, { align: 'right' });

  y += 18;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.gold);
  doc.text('Leak Distribution', 20, y);
  y += 8;

  for (const p of result.pillars) {
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.white);
    doc.text(safe(p.name + ': ' + Math.round(p.leakPercentage) + '%'), 20, y);

    const barWidth = Math.max(2, (p.leakPercentage / 100) * 100);
    doc.setFillColor(...getRiskColor(p.risk));
    doc.rect(80, y - 3, barWidth, 4, 'F');
    y += 7;
  }

  drawFooter(doc);

  // === PAGE 2: Detailed Breakdown ===
  doc.addPage();
  drawBg(doc);

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.gold);
  doc.text('DETAILED BREAKDOWN', 105, 25, { align: 'center' });

  y = 40;

  for (const pillar of result.pillars) {
    const copy = getPillarCopy(pillar.id, pillar.score);
    const riskColor = getRiskColor(pillar.risk);

    if (y > 230) {
      doc.addPage();
      drawBg(doc);
      y = 25;
    }

    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.white);
    doc.text(safe(pillar.name), 20, y);

    doc.setFontSize(9);
    doc.setTextColor(...riskColor);
    doc.text(pillar.risk + ' RISK', 120, y);

    doc.setTextColor(...COLORS.gold);
    doc.text('$' + pillar.leakAmount.toLocaleString() + '/year', 160, y);
    y += 7;

    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.lightGray);
    doc.text('Your Answer:', 20, y);
    doc.setFont('helvetica', 'normal');
    doc.text(safe(getSelectedAnswer(pillar.id, scores)), 48, y);
    y += 6;

    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.lightGray);
    doc.text('Insight:', 20, y);
    y += 4;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    const diagLines = wrap(doc, copy.diagnosis, 170);
    doc.text(diagLines, 20, y);
    y += diagLines.length * 4 + 3;

    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.gold);
    doc.text('DIY Action:', 20, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.white);
    const fixLines = wrap(doc, copy.fix, 150);
    doc.text(fixLines, 48, y);
    y += fixLines.length * 4 + 5;

    drawLine(doc, y);
    y += 8;
  }

  y += 3;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.white);
  const recoveryLines = wrap(
    doc,
    'Even if you recovered just half of this over the next 12 months, that\'s an extra $' + result.halfLeak.toLocaleString() + ' in profit - without increasing ad spend or working more hours.',
    170
  );
  doc.text(recoveryLines, 20, y);

  drawFooter(doc);

  // === PAGE 3: Action Plan ===
  doc.addPage();
  drawBg(doc);

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.gold);
  doc.text('YOUR ACTION PLAN', 105, 25, { align: 'center' });

  doc.setFontSize(11);
  doc.setTextColor(...COLORS.white);
  doc.text(safe("Here's what you should do right now to fix this:"), 20, 38);

  y = 50;

  const actionSteps = [
    { title: 'Install an AI follow-up assistant', desc: 'Set up automated follow-up across email, SMS, and social DMs so no lead goes cold.' },
    { title: 'Build a lead magnet funnel', desc: 'Create a simple funnel to generate consistent inbound prospects on autopilot.' },
    { title: 'Automate booking and nurture', desc: 'Use automated booking + nurture systems to prevent lost opportunities.' },
    { title: 'Launch a retention funnel', desc: 'Set up referrals, upsells, and testimonial collection to maximize client lifetime value.' },
  ];

  for (let i = 0; i < actionSteps.length; i++) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.gold);
    doc.text(safe((i + 1) + '. ' + actionSteps[i].title), 20, y);
    y += 7;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.lightGray);
    const descLines = wrap(doc, actionSteps[i].desc, 170);
    doc.text(descLines, 20, y);
    y += descLines.length * 4 + 8;
  }

  const biggestCopy = getPillarCopy(result.biggestLeakPillar.id, result.biggestLeakPillar.score);
  y += 5;
  doc.setFillColor(30, 30, 30);
  doc.setDrawColor(...COLORS.gold);
  doc.roundedRect(20, y, 170, 25, 3, 3, 'FD');

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.white);
  doc.text('If you only fix ONE thing in the next 30 days, fix this:', 25, y + 10);

  doc.setTextColor(...COLORS.gold);
  const priorityLines = wrap(doc, '-> ' + biggestCopy.fix, 160);
  doc.text(priorityLines, 25, y + 18);

  drawFooter(doc);

  // === PAGE 4: Next Steps ===
  doc.addPage();
  drawBg(doc);

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.gold);
  doc.text('NEXT STEPS', 105, 25, { align: 'center' });

  y = 45;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.white);
  doc.text('Option 1: Figure It Out Yourself', 20, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.lightGray);
  const opt1 = wrap(doc, "Use this report as a roadmap. 6-12 months of trial and error, you're still the bottleneck. Cost: your time and every dollar that leaks while you build.", 170);
  doc.text(opt1, 20, y);
  y += opt1.length * 4 + 8;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.white);
  doc.text('Option 2: Hire Separate Agencies', 20, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.lightGray);
  const opt2 = wrap(doc, "One for each system. $8K-$25K/month, 12+ months, you become the project manager. Cost: retainers + you're still the bottleneck.", 170);
  doc.text(opt2, 20, y);
  y += opt2.length * 4 + 8;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.gold);
  doc.text('Option 3: Let Us Show You How to Patch These Leaks - Starting Today', 20, y);
  y += 8;

  drawLine(doc, y);
  y += 8;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.gold);
  doc.text('BOOK A LIVE STRATEGY SESSION', 20, y);
  y += 6;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.lightGray);
  doc.text('We walk through this report together, map out your 30-90 day fix plan starting with your #1 leak.', 20, y);
  y += 5;
  doc.text('No charge, no obligation. Bring your downloaded PDF report to the call.', 20, y);
  y += 5;
  doc.setTextColor(...COLORS.cyan);
  doc.textWithLink('https://profitleakfix.com/audit-calendar-yt', 20, y, {
    url: 'https://profitleakfix.com/audit-calendar-yt',
  });
  y += 15;

  drawLine(doc, y);
  y += 8;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...COLORS.lightGray);
  const closing = wrap(doc, '"Every day you wait is another day this revenue leaks. The money is already flowing through your business. Now decide how fast you want to collect it."', 170);
  doc.text(closing, 20, y);

  drawFooter(doc);

  return doc.output('blob');
}
